# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Minchul Shin's Blog
email: min.stellastra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
author: Minchul Shin
about: Artificial Intelligence researcher. Research topic is deep learning and Human-robot interaction(HRI).
banner-title: Going deeper with daily effort
blog-header: M.C.Shin's Reasearch blog of Artificial Intelligence and Deep Learning.
github: https://github.com/nashory
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nashory.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stellastra
github_username:  nashory

disqus_shortname: nashory
google_analytics: UA-XXXXXXXX-Y
avatar_url: /assets/img/profile.jpg

# Build settings
highlighter: rouge
markdown: kramdown
theme: minima
gems:
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 20
per_page: 20
paginate_path: "/page/:num/"

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/stellastra"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/minchul-shin-16656213b"
    - icon: fa-github
      link: "https://github.com/nashory"


compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
